stage_dict ={
	"2": "Fountain of Dreams",
	"3": "Pokemon Stadium",
	"4": "Princess Peach's Castle",
	"5": "Kongo Jungle",
	"6": "Brinstar",
	"7": "Corneria",
	"8": "Yoshi's Story",
	"9": "Onett",
	"10": "Mute City",
	"11": "Rainbow Cruise",
	"12": "Jungle Japes",
	"13": "Great Bay",
	"14": "Hyrule Temple",
	"15": "Brinstar Depths",
	"16": "Yoshi's Island",
	"17": "Green Greens",
	"18": "Fourside",
	"19": "Mushroom Kingdom I",
	"20": "Mushroom Kingdom II",
	"22": "Venom",
	"23": "Poké Floats",
	"24": "Big Blue",
	"25": "Icicle Mountain",
	"26": "Icetop",
	"27": "Flat Zone",
	"28": "Dream Land N64",
	"29": "Yoshi's Island N64",
	"30": "Kongo Jungle N64",
	"31": "Battlefield",
	"32": "Final Destination",
	"33": "Target Test (Mario)",
	"34": "Target Test (Captain Falcon)",
	"35": "Target Test (Young Link)",
	"36": "Target Test (Donkey Kong)",
	"37": "Target Test (Dr. Mario)",
	"38": "Target Test (Falco)",
	"39": "Target Test (Fox)",
	"40": "Target Test (Ice Climbers)",
	"41": "Target Test (Kirby)",
	"42": "Target Test (Bowser)",
	"43": "Target Test (Link)",
	"44": "Target Test (Luigi)",
	"45": "Target Test (Marth)",
	"46": "Target Test (Mewtwo)",
	"47": "Target Test (Ness)",
	"48": "Target Test (Peach)",
	"49": "Target Test (Pichu)",
	"50": "Target Test (Pikachu)",
	"51": "Target Test (Jigglypuff)",
	"52": "Target Test (Samus)",
	"53": "Target Test (Sheik)",
	"54": "Target Test (Yoshi)",
	"55": "Target Test (Zelda)",
	"56": "Target Test (Mr. Game & Watch)",
	"57": "Target Test (Roy)",
	"58": "Target Test (Ganondorf)",
	"84": "Home-Run Contest",
  "306": "Gamecube Realm",
  "301": "Delfino Plaza",
  "303": "Luigi's Mansion",
  "308": "Dedede Arena",
  "307": "Sprout Tower",
  "304": "Fichina",
  "309": "Saturn Valley",
  "302": "Green Hill Zone",
  "300": "Village",
  "305": "Dolphin Park",
  "288": "Peach's Castle",
  "289": "Hyrule Castle",
  "291": "Planet Zebes",
  "292": "Mushroom Kingdom",
  "293": "Meta Crystal",
  "312": "Sector Z",
  "290": "Saffron City"
}

character_dict ={
  "0": {
    "name": "Captain Falcon",
    "shortName": "Falcon",
    "colors": ["Black", "Red", "White", "Green", "Blue"]
  },
  "1": {
    "name": "Donkey Kong",
    "shortName": "DK",
    "colors": ["Black", "Red", "Blue", "Green"]
  },
  "2": {
    "name": "Fox",
    "colors": ["Red", "Blue", "Green"]
  },
  "3": {
    "name": "Mr. Game & Watch",
    "shortName": "G&W",
    "colors": ["Red", "Blue", "Green"]
  },
  "4": {
    "name": "Kirby",
    "colors": ["Yellow", "Blue", "Red", "Green", "White"]
  },
  "5": {
    "name": "Bowser",
    "colors": ["Red", "Blue", "Black"]
  },
  "6": {
    "name": "Link",
    "colors": ["Red", "Blue", "Black", "White"]
  },
  "7": {
    "name": "Luigi",
    "colors": ["White", "Blue", "Red"]
  },
  "8": {
    "name": "Mario",
    "colors": ["Yellow", "Black", "Blue", "Green"]
  },
  "9": {
    "name": "Marth",
    "colors": ["Red", "Green", "Black", "White"]
  },
  "10": {
    "name": "Mewtwo",
    "colors": ["Red", "Blue", "Green"]
  },
  "11": {
    "name": "Ness",
    "colors": ["Yellow", "Blue", "Green"]
  },
  "12": {
    "name": "Peach",
    "colors": ["Daisy", "White", "Blue", "Green"]
  },
  "13": {
    "name": "Pikachu",
    "colors": ["Red", "Party Hat", "Cowboy Hat"]
  },
  "14": {
    "name": "Ice Climbers",
    "shortName": "ICs",
    "colors": ["Green", "Orange", "Red"]
  },
  "15": {
    "name": "Jigglypuff",
    "shortName": "Puff",
    "colors": ["Red", "Blue", "Headband", "Crown"]
  },
  "16": {
    "name": "Samus",
    "colors": ["Pink", "Black", "Green", "Purple"]
  },
  "17": {
    "name": "Yoshi",
    "colors": ["Red", "Blue", "Yellow", "Pink", "Cyan"]
  },
  "18": {
    "name": "Zelda",
    "colors": ["Red", "Blue", "Green", "White"]
  },
  "19": {
    "name": "Sheik",
    "colors": ["Red", "Blue", "Green", "White"]
  },
  "20": {
    "name": "Falco",
    "colors": ["Red", "Blue", "Green"]
  },
  "21": {
    "name": "Young Link",
    "shortName": "YLink",
    "colors": ["Red", "Blue", "White", "Black"]
  },
  "22": {
    "name": "Dr. Mario",
    "shortName": "Doc",
    "colors": ["Red", "Blue", "Green", "Black"]
  },
  "23": {
    "name": "Roy",
    "colors": ["Red", "Blue", "Green", "Yellow"]
  },
  "24": {
    "name": "Pichu",
    "colors": ["Red", "Blue", "Green"]
  },
  "25": {
    "name": "Ganondorf",
    "shortName": "Ganon",
    "colors": ["Red", "Blue", "Green", "Purple"]
  },
  "26": {
    "name": "Wolf"
  },
  "27": {
    "name": "Diddy Kong"
  },
  "28": {
    "name": "Charizard"
  },
  "29": {
    "name": "Lucas"
  },
  "30": {
    "name": "Sonic"
  },
  "31": {
    "name": "King Dedede"
  },
  "32": {
    "name": "Tails"
  }
}

move_dict = {
  "1": {
    "name": "Miscellaneous",
    "shortName": "misc"
  },
  "2": {
    "name": "Jab",
    "shortName": "jab"
  },
  "3": {
    "name": "Jab",
    "shortName": "jab"
  },
  "4": {
    "name": "Jab",
    "shortName": "jab"
  },
  "5": {
    "name": "Rapid Jabs",
    "shortName": "rapid-jabs"
  },
  "6": {
    "name": "Dash Attack",
    "shortName": "dash"
  },
  "7": {
    "name": "Forward Tilt",
    "shortName": "ftilt"
  },
  "8": {
    "name": "Up Tilt",
    "shortName": "utilt"
  },
  "9": {
    "name": "Down Tilt",
    "shortName": "dtilt"
  },
  "10": {
    "name": "Forward Smash",
    "shortName": "fsmash"
  },
  "11": {
    "name": "Up Smash",
    "shortName": "usmash"
  },
  "12": {
    "name": "Down Smash",
    "shortName": "dsmash"
  },
  "13": {
    "name": "Neutral Air",
    "shortName": "nair"
  },
  "14": {
    "name": "Forward Air",
    "shortName": "fair"
  },
  "15": {
    "name": "Back Air",
    "shortName": "bair"
  },
  "16": {
    "name": "Up Air",
    "shortName": "uair"
  },
  "17": {
    "name": "Down Air",
    "shortName": "dair"
  },
  "18": {
    "name": "Neutral B",
    "shortName": "neutral-b"
  },
  "19": {
    "name": "Side B",
    "shortName": "side-b"
  },
  "20": {
    "name": "Up B",
    "shortName": "up-b"
  },
  "21": {
    "name": "Down B",
    "shortName": "down-b"
  },
  "50": {
    "name": "Getup Attack",
    "shortName": "getup"
  },
  "51": {
    "name": "Getup Attack (Slow)",
    "shortName": "getup-slow"
  },
  "52": {
    "name": "Grab Pummel",
    "shortName": "pummel"
  },
  "53": {
    "name": "Forward Throw",
    "shortName": "fthrow"
  },
  "54": {
    "name": "Back Throw",
    "shortName": "bthrow"
  },
  "55": {
    "name": "Up Throw",
    "shortName": "uthrow"
  },
  "56": {
    "name": "Down Throw",
    "shortName": "dthrow"
  },
  "57": {
    "name": "Cargo Forward Throw",
    "shortName": "cargo-forward"
  },
  "59": {
    "name": "Cargo Up Throw",
    "shortName": "cargo-up"
  },
  "61": {
    "name": "Edge Attack (Slow)",
    "shortName": "edge-slow"
  },
  "62": {
    "name": "Edge Attack",
    "shortName": "edge"
  }
}

character_movenames_dict ={
  "Captain Falcon" : {
    "1": "Item Throw",
    "2": "Jab",
    "3": "Straight",
    "4": "Knee",
    "5": "Mach Punch",
    "6": "Turbo Shoulder",
    "7": "Round Kick",
    "8": "Wheel Kick",
    "9": "Crouching Kick",
    "10": "Overheat Elbow",
    "11": "Pinwheel Kick",
    "12": "Pendulum Kick",
    "13": "Rotary Kick",
    "14": "Knee Smash",
    "15": "Reverse Knuckle",
    "16": "Overhead Kick",
    "17": "Step on it",
    "18": "Falcon Punch",
    "19": "Raptor Boost",
    "20": "Falcon Dive",
    "21": "Falcon Kick",
    "50": "Getup Attack",
    "51": "Getup Attack",
    "52": "Captive Knee",
    "53": "Body Blow",
    "54": "Kickback",
    "55": "Rising Palm",
    "56": "Throw Down",
    "61": "Edge Attack",
    "62": "Edge Attack",
    },
  "Fox": {
    "1": "Item Throw",
    "2": "Jab",
    "3": "Straight",
    "5": "Rapid Kick",
    "6": "Jumping Side Kick",
    "7": "Fox Kick",
    "8": "Back Kick",
    "9": "Fox Tail",
    "10": "Roundhouse Kick",
    "11": "Flip Kick",
    "12": "Fox Split",
    "13": "Flying Kick",
    "14": "Tornado Kick",
    "15": "Reverse Spin Kick",
    "16": "McCloud Flip",
    "17": "Air Drill",
    "18": "Blaster",
    "19": "Fox Illusion",
    "20": "Fire Fox",
    "21": "Reflector",
    "50": "Getup Attack",
    "51": "Getup Attack",
    "52": "Knee",
    "53": "Elbow Bash",
    "54": "Skeet Blaster",
    "55": "Star Blaster",
    "56": "Floor Blaster",
    "61": "Edge Attack",
    "62": "Edge Attack",
  },
  "Donkey Kong": {
    "1": "Item Throw",
    "2": "Swipe",
    "3": "Uppercut",
    "6": "Konga Kick",
    "7": "Backhand Slap",
    "8": "Spider Web Swipe",
    "9": "Slouch Slap",
    "10": "Kong Klap",
    "11": "Ape Applause",
    "12": "Twin Beat",
    "13": "Kong Whirl",
    "14": "Hammer Knuckle",
    "15": "Back Kick",
    "16": "Flying Headbutt",
    "17": "Flying Stomp",
    "18": "Giant Punch",
    "19": "Headbutt",
    "20": "Spinning Kong",
    "21": "Hand Slap",
    "50": "Getup Attack",
    "51": "Getup Attack",
    "52": "Jungle Chop",
    "53": "Kong Karry",
    "54": "Donkey Fling",
    "55": "Coconut Toss",
    "56": "Simian Slam",
    "57": "Cargo Throw",
    "58": "Cargo Throw",
    "59": "Cargo Throw",
    "61": "Edge Attack",
    "62": "Edge Attack",
  },
  "Mr. Game & Watch": {
    "1": "Item Throw",
    "2": "Green House",
    "5": "Green House",
    "6": "Helmet",
    "7": "Lion",
    "8": "Flag Man",
    "9": "Manhole",
    "10": "Fire Attack",
    "11": "Octopus",
    "12": "Vermin",
    "13": "Parachute",
    "14": "Cement Factory",
    "15": "Turtle Bridge",
    "16": "Spit Ball Sparky",
    "17": "Donkey Kong Jr",
    "18": "Chef",
    "19": "Judgement",
    "20": "Fire",
    "21": "Oil Panic",
    "50": "Getup Attack",
    "51": "Getup Attack",
    "52": "Alarm",
    "53": "Forward Ball",
    "54": "Backward Ball",
    "55": "Vertical Ball",
    "56": "Drop Ball",
    "61": "Edge Attack",
    "62": "Edge Attack",
  },
  "Mario": {
    "1": "Item Throw",
    "2": "Left Jab",
    "3": "Right Cross",
    "4": "Toe Kick",
    "6": "Slide",
    "7": "Plumber Kick",
    "8": "Uppercut",
    "9": "Leg Sweep",
    "10": "Fire Glove",
    "11": "Lead Headbutt",
    "12": "Breakdance Sweep",
    "13": "Plumber’s Boot",
    "14": "Plunger",
    "15": "Drop Kick",
    "16": "Bicycle Kick",
    "17": "Drill Kick",
    "52": "Clutch Headbutt",
    "53": "Heave-Ho",
    "54": "Airplane Swing",
    "55": "Mario Launch",
    "56": "Down the Drain",
    "18": "Fireball",
    "19": "Cape",
    "20": "Super Jump Punch",
    "21": "Mario Tornado",
    "50": "Getup Attack",
    "51": "Getup Attack",
    "61": "Edge Attack",
    "62": "Edge Attack",
  },
  "Pikachu": {
    "1": "Item Throw",
    "2": "Headbutt",
    "6": "Running Headbutt",
    "7": "Pika Kick",
    "8": "Tail Smack",
    "9": "Tail Sweep",
    "10": "Thundershock",
    "11": "Tail Somersault",
    "12": "Electric Flower",
    "13": "Pika Roll",
    "14": "Electric Drill",
    "15": "Glider",
    "16": "Tail Chop",
    "17": "Electric Screw",
    "52": "Electric Shock",
    "53": "Electrocution",
    "54": "Submission",
    "55": "Electric Skull",
    "56": "Electric Slam",
    "18": "Thunder Jolt",
    "19": "Skull Bash",
    "20": "Quick Attack",
    "21": "Thunder",
    "50": "Getup Attack",
    "51": "Getup Attack",
    "61": "Edge Attack",
    "62": "Edge Attack",
  },
  "Bowser": {
    "1": "Item Throw",
    "2": "Left Scratch",
    "3": "Right Scratch",
    "6": "Horn Charge",
    "7": "Koopa Knuckle",
    "8": "Ceiling Scratch Floor",
    "9": "Scratch",
    "10": "Hammer Head",
    "11": "Shell Shock",
    "12": "Buzzsaw",
    "13": "Gyroscope",
    "14": "Jump Slash",
    "15": "Spike Stretch",
    "16": "Horn Toss",
    "17": "Scrub Brush",
    "52": "Bull Horns",
    "53": "Catapult",
    "54": "Reverse Throw",
    "55": "Blender",
    "56": "Bowser Slam",
    "18": "Fire Breath",
    "19": "Koopa Klaw",
    "20": "Whirling Fortress",
    "21": "Bowser Bomb",
    "50": "Getup Attack",
    "51": "Getup Attack",
    "61": "Edge Attack",
    "62": "Edge Attack",
  },
  "Peach": {
    "1": "Item Throw",
    "2": "Royal Slap",
    "3": "Double Royal Slap",
    "6": "Lady Push",
    "7": "Can-Can Kick",
    "8": "Crown Bash",
    "9": "Elegant Sweep",
    "10": "Peach Swing",
    "11": "Pirouette",
    "12": "Double-Edged Gown",
    "13": "Princess Twirl",
    "14": "Crown Smack",
    "15": "Flying Hip",
    "16": "Floating High Kick",
    "17": "Stiletto Kick",
    "52": "Heel Stomp",
    "53": "Royal Slap",
    "54": "Gut Punch",
    "55": "The Royal Treatment",
    "18": "Toad",
    "19": "Peach Bomber",
    "20": "Peach Parasol",
    "21": "Vegetable",
    "50": "Getup Attack",
    "51": "Getup Attack",
    "61": "Edge Attack",
    "62": "Edge Attack"
  },
  "Yoshi": {
    "1": "Item Throw",
    "2": "Left Kick",
    "3": "Right Kick",
    "6": "Noggin Knock",
    "7": "Dino Kick",
    "8": "Tail Snap",
    "9": "Tail Sweep",
    "10": "Noggin Floggin'",
    "11": "Jumping Headbutt",
    "12": "Double Tail Whip",
    "13": "Yoshi's Kick",
    "14": "Noggin Dunk",
    "15": "Tail Wag",
    "16": "Dino Flip",
    "17": "Flutter Kick",
    "52": "Chew",
    "53": "Spit Out",
    "54": "Spin 'n' Spit",
    "55": "Spit Up",
    "56": "Jump 'n' Spit",
    "18": "Egg Lay",
    "19": "Egg Roll",
    "20": "Egg Throw",
    "21": "Yoshi Bomb",
    "50": "Getup Attack",
    "51": "Getup Attack",
    "61": "Edge Attack",
    "62": "Edge Attack"
},
"Ness": {
    "1": "Item Throw",
    "2": "Hook",
    "3": "Straight",
    "4": "Kick",
    "6": "PK Shove",
    "7": "Short Kick",
    "8": "Push Up",
    "9": "Squat Kick",
    "10": "Home Run Swing",
    "11": "Around the World",
    "12": "Walk the Dog",
    "13": "Ness Spin",
    "14": "Flying PK Shove",
    "15": "PK Drop Kick",
    "16": "Jumping Headbutt",
    "17": "Meteor Kick",
    "52": "Captive Headbutt",
    "53": "PK Throw",
    "54": "Reverse PK Throw",
    "55": "Cowboy PK Throw",
    "56": "PK Inferno",
    "18": "PK Flash",
    "19": "PK Fire",
    "20": "PK Thunder",
    "21": "PSI Magnet",
    "50": "Getup Attack",
    "51": "Getup Attack",
    "61": "Edge Attack",
    "62": "Edge Attack"
},
"Ice Climbers": {
    "1": "Item Throw",
    "2": "Pound",
    "3": "Upswing",
    "6": "Scoop",
    "7": "Hammer Swing",
    "8": "Hammer Spin",
    "9": "Shin Attack",
    "10": "Ice Hammer",
    "11": "Icicle Crasher",
    "12": "Hammer Sweep",
    "13": "Icy Whirlwind",
    "14": "Hammer Slam",
    "15": "Reverse Swing",
    "16": "Hammer Reach",
    "17": "Hammer Ride",
    "52": "Cold Headbutt",
    "53": "Hockey Slapshot",
    "54": "Snow Mt. Throw",
    "55": "Icicle Toss",
    "56": "Avalanche Crusher",
    "18": "Ice Shot",
    "19": "Squall Hammer",
    "20": "Belay",
    "21": "Blizzard",
    "50": "Getup Attack",
    "51": "Getup Attack",
    "61": "Edge Attack",
    "62": "Edge Attack"
},
"Kirby": {
    "1": "Item Throw",
    "2": "Right Punch",
    "3": "Left Punch",
    "5": "Vulcan Jab",
    "6": "Fire Kirby",
    "7": "Spinning Kick",
    "8": "Back Kick",
    "9": "Squish Kick",
    "10": "Smash Kick",
    "11": "Kirby Flip Kick",
    "12": "Propeller Kick",
    "13": "Twinkle Star",
    "14": "Spiral Kick",
    "15": "Drop Kick",
    "16": "Floating Flip Kick",
    "17": "Screw Driver",
    "52": "Slap",
    "53": "Power Bomb",
    "54": "Brain Buster",
    "55": "Ninja Drop",
    "56": "Victory Dance",
    "18": "Swallow",
    "19": "Hammer",
    "20": "Final Cutter",
    "21": "Stone",
    "50": "Getup Attack",
    "51": "Getup Attack",
    "61": "Edge Attack",
    "62": "Edge Attack"
},
"Samus": {
    "1": "Item Throw",
    "2": "Straight",
    "3": "Cannon Hammer",
    "6": "Shoulder Tackle",
    "7": "Spin Kick",
    "8": "Heel Kick",
    "9": "Earth Blaster",
    "10": "Cannon Lunge",
    "11": "Cover Fire",
    "12": "Spinning Leg Sweep",
    "13": "Chozo Kick",
    "14": "Aerial Fire",
    "15": "Flying Back Kick",
    "16": "Drill Kick",
    "17": "Meteor Cannon",
    "52": "Chozo Chop",
    "53": "Beam Throw",
    "54": "Reverse Beam Throw",
    "55": "Beam Launch",
    "56": "Beam Slam",
    "18": "Charge Shot",
    "19": "Missile",
    "20": "Screw Attack",
    "21": "Bomb",
    "50": "Getup Attack",
    "51": "Getup Attack",
    "61": "Edge Attack",
    "62": "Edge Attack"
},
"Zelda": {
    "1": "Item Throw",
    "2": "Short Flash",
    "3": "Magical Push",
    "6": "Mystic Swipe",
    "7": "Protective Sweep",
    "8": "Trip",
    "9": "Shining Palm",
    "10": "Power Sweep",
    "11": "Compass Spin",
    "12": "Magic Spin",
    "13": "Lightning Kick",
    "14": "Reverse Lightning Kick",
    "15": "Condensed Blast",
    "16": "Meteor Heel",
    "17": "Magical Hold",
    "52": "Hex",
    "53": "Levitation",
    "54": "Reverse Levitation",
    "55": "Levitation Launch",
    "56": "Plasma Beat",
    "18": "Nayru's Love",
    "19": "Din's Fire",
    "20": "Farore's Wind",
    "21": "Transform",
    "50": "Getup Attack",
    "51": "Getup Attack",
    "61": "Edge Attack",
    "62": "Edge Attack"
},
"Sheik": {
    "1": "Item Throw",
    "2": "Slicing Blade",
    "3": "Cutting Blade",
    "5": "Piercing Blade",
    "6": "Gale Form",
    "7": "Wheel Kick",
    "8": "Bow Form",
    "9": "Crouching Sweep",
    "10": "Double Snake",
    "11": "Razor Wing",
    "12": "Windmill",
    "13": "Falling Leaves",
    "14": "Hatchet",
    "15": "Flying Swallow",
    "16": "Vortex Form",
    "17": "Butcher Bird",
    "52": "Forearm",
    "53": "Battering Ram",
    "54": "Backlash",
    "55": "Standing Crane",
    "56": "Guillotine",
    "18": "Transform",
    "19": "Needle Storm",
    "20": "Chain",
    "21": "Vanish",
    "50": "Getup Attack",
    "51": "Getup Attack",
    "61": "Edge Attack",
    "62": "Edge Attack"
},
"Link": {
    "1": "Item Throw",
    "2": "Slash",
    "3": "Counter Slash",
    "4": "Stab",
    "5": "Illusion Stab",
    "6": "Running Hack",
    "7": "Sword Chop",
    "8": "Half-Moon Swipe",
    "9": "Grass Cutter",
    "10": "Sword Slice",
    "11": "Triple Sword Swipe",
    "12": "Sword Sweep",
    "13": "Hylian Kick",
    "14": "Spinning Sword",
    "15": "Double Kick",
    "16": "Stab-Up",
    "17": "Sword Plant",
    "52": "Hit Strike",
    "53": "Kick Out",
    "54": "Reverse Kick Out",
    "55": "Sword Launch",
    "56": "Flying Elbow",
    "18": "Bow",
    "19": "Boomerang",
    "20": "Spin Attack",
    "21": "Bomb",
    "50": "Getup Attack",
    "51": "Getup Attack",
    "61": "Edge Attack",
    "62": "Edge Attack"
},
"Jigglypuff": {
    "1": "Item Throw",
    "2": "Left Jab",
    "3": "Right Jab",
    "6": "Jiggly Ram",
    "7": "Rolling Kick",
    "8": "Back Kick",
    "9": "Trip",
    "10": "Lunge Kick",
    "11": "Headbutt",
    "12": "Jiggly Split",
    "13": "Jigglypuff Kick",
    "14": "Drop Kick",
    "15": "Spinning Back Kick",
    "16": "Mow Down",
    "17": "Spinning Kick",
    "52": "Slap",
    "53": "Bumper",
    "54": "Back Buster",
    "55": "Puff Launch",
    "56": "Grinder",
    "18": "Rollout",
    "19": "Pound",
    "20": "Sing",
    "21": "Rest",
    "50": "Getup Attack",
    "51": "Getup Attack",
    "61": "Edge Attack",
    "62": "Edge Attack"
},
"Mewtwo": {
    "1": "Item Throw",
    "2": "Dark Flash",
    "5": "Dark Flame",
    "6": "Dark Torch",
    "7": "Tail Whip",
    "8": "Flip",
    "9": "Tail Sweep",
    "10": "Shadow Blast",
    "11": "Galaxy Force",
    "12": "Shadow Bomb",
    "13": "Body Spark",
    "14": "Shadow Scratch",
    "15": "Tail Flick",
    "16": "Somersault Kick",
    "17": "Meteor Kick",
    "52": "Dark Shock",
    "53": "Shadow Cannon",
    "54": "Telekinesis",
    "55": "Psychic Whirlwind",
    "56": "Tail Slap",
    "18": "Shadow Ball",
    "19": "Confusion",
    "20": "Teleport",
    "21": "Disable",
    "50": "Getup Attack",
    "51": "Getup Attack",
    "61": "Edge Attack",
    "62": "Edge Attack"
},
"Luigi": {
    "1": "Item Throw",
    "2": "Left Jab",
    "3": "Right Jab",
    "4": "Plumber’s Rump",
    "6": "Fists of Fear",
    "7": "Plumber Kick",
    "8": "Cat Punch",
    "9": "Heel Kick",
    "10": "Trowel Stab",
    "11": "Lead Headbutt",
    "12": "Breakdance Sweep",
    "13": "Plumber’s Boot",
    "14": "Chop Chop",
    "15": "Drop Kick",
    "16": "Bicycle Kick",
    "17": "Screwdriver Kick",
    "52": "Clutch Headbutt",
    "53": "Heave-Ho",
    "54": "Airplane Swing",
    "55": "Luigi Launch",
    "56": "Down the Drain",
    "18": "Fireball",
    "19": "Green Missile",
    "20": "Super Jump Punch",
    "21": "Luigi Cyclone",
    "50": "Getup Attack",
    "51": "Getup Attack",
    "61": "Edge Attack",
    "62": "Edge Attack"
},
"Marth": {
    "1": "Item Throw",
    "2": "Slash",
    "3": "Counter Slash",
    "6": "Raid Chop",
    "7": "Sharp Edge",
    "8": "Anti-Air Slash",
    "9": "Low Stab",
    "10": "Dragon Killer",
    "11": "Justice Sword",
    "12": "Whirlwind Blade",
    "13": "Double Slash",
    "14": "Aerial Swipe",
    "15": "About Face",
    "16": "Luna Slash",
    "17": "Half Moon",
    "52": "Knee",
    "53": "Bounce",
    "54": "Throw Away",
    "55": "Emblem Toss",
    "56": "Slam",
    "18": "Shield Breaker",
    "19": "Dancing Blade",
    "20": "Dolphin Slash",
    "21": "Counter",
    "50": "Getup Attack",
    "51": "Getup Attack",
    "61": "Edge Attack",
    "62": "Edge Attack"
},
"Dr. Mario": {
    "1": "Item Throw",
    "2": "Left Jab",
    "3": "Right Cross",
    "4": "Toe Kick",
    "6": "Slide",
    "7": "Dr. Kick",
    "8": "Uppercut",
    "9": "Reflex Test",
    "10": "Defibrillator",
    "11": "Ear, Nose and Throat",
    "12": "Surgical Sweep",
    "13": "Dr. Kick",
    "14": "Dr. Punch",
    "15": "Drop Kick, M.D.",
    "16": "Bicycle Kick",
    "17": "Bone Drill",
    "52": "Eye Exam",
    "53": "Routine Physical",
    "54": "Traction",
    "55": "Check Up",
    "56": "Hospital Bed",
    "18": "Megavitamins",
    "19": "Super Sheet",
    "20": "Super Jump Punch",
    "21": "Dr. Tornado",
    "50": "Getup Attack",
    "51": "Getup Attack",
    "61": "Edge Attack",
    "62": "Edge Attack"
},
"Ganondorf": {
    "1": "Item Throw",
    "2": "Thunder Punch",
    "6": "Iron Shoulder",
    "7": "Armor Crusher",
    "8": "Volcano Kick",
    "9": "Sweeping Snake",
    "10": "Nightmare Lunge",
    "11": "Tornado Kick",
    "12": "Leg Whip",
    "13": "Swooping Keese",
    "14": "Skull Crusher",
    "15": "Hidden Gauntlet",
    "16": "Vulture Kick",
    "17": "Thunder Drop",
    "52": "Armored Knee",
    "53": "Gut Punch",
    "54": "Blind Mule Kick",
    "55": "Jaw Breaker",
    "56": "Dirt Nap",
    "18": "Warlock Punch",
    "19": "Gerudo Dragon",
    "20": "Dark Dive",
    "21": "Wizard’s Foot",
    "50": "Getup Attack",
    "51": "Getup Attack",
    "61": "Edge Attack",
    "62": "Edge Attack"
},
"Young Link": {
    "1": "Item Throw",
    "2": "Slash",
    "3": "Counter Slash",
    "4": "Stab",
    "5": "Illusion Stab",
    "6": "Running Hack",
    "7": "Sword Chop",
    "8": "Half-Moon Swipe",
    "9": "Grass Cutter",
    "10": "Sword Slice",
    "11": "Triple Sword Swipe",
    "12": "Sword Sweep",
    "13": "Hylian Kick",
    "14": "Spinning Sword",
    "15": "Double Kick",
    "16": "Stab Up",
    "17": "Sword Plant",
    "52": "Hit Strike",
    "53": "Kick Out",
    "54": "Reverse Kick Out",
    "55": "Sword Launch",
    "56": "Flying Elbow",
    "18": "Fire Bow",
    "19": "Boomerang",
    "20": "Spin Attack",
    "21": "Bomb",
    "50": "Getup Attack",
    "51": "Getup Attack",
    "61": "Edge Attack",
    "62": "Edge Attack"
},
"Falco": {
    "1": "Item Throw",
    "2": "Jab",
    "3": "Straight",
    "5": "Rapid Kick",
    "6": "Jumping Side Kick",
    "7": "Bird Kick",
    "8": "Back Kick",
    "9": "Bird Sweep",
    "10": "Roundhouse Kick",
    "11": "Flip Kick",
    "12": "Falco Split",
    "13": "Flying Kick",
    "14": "Cyclone Kick",
    "15": "Reverse Spin Kick",
    "16": "Falco Flip",
    "17": "Air Drill",
    "52": "Knee",
    "53": "Elbow Bash",
    "54": "Skeet Blaster",
    "55": "Star Blaster",
    "56": "Floor Blaster",
    "18": "Blaster",
    "19": "Falco Phantasm",
    "20": "Fire Bird",
    "21": "Reflector",
    "50": "Getup Attack",
    "51": "Getup Attack",
    "61": "Edge Attack",
    "62": "Edge Attack"
},
"Pichu": {
    "1": "Item Throw",
    "2": "Headbutt",
    "6": "Running Headbutt",
    "7": "Pichu Kick",
    "8": "Tail Smack",
    "9": "Tail Sweep",
    "10": "Thundershock",
    "11": "Jumping Headbutt",
    "12": "Spinning Mouse",
    "13": "Pichu Roll",
    "14": "Electric Drill",
    "15": "Glider",
    "16": "Tail Chop",
    "17": "Electric Screw",
    "52": "Electric Shock",
    "53": "Electrocution",
    "54": "Submission",
    "55": "Electric Skull",
    "56": "Electric Slam",
    "18": "Thunder Jolt",
    "19": "Skull Bash",
    "20": "Quick Attack",
    "21": "Thunder",
    "50": "Getup Attack",
    "51": "Getup Attack",
    "61": "Edge Attack",
    "62": "Edge Attack"
},
"Roy": {
    "1": "Item Throw",
    "2": "Slash",
    "6": "Raid Chop",
    "7": "Sharp Edge",
    "8": "Anti-Air Slash",
    "9": "Low Stab",
    "10": "Dragon Killer",
    "11": "Flame Sword",
    "12": "Whirlwind Blade",
    "13": "Double Slash",
    "14": "Aerial Swipe",
    "15": "About Face",
    "16": "Luna Slash",
    "17": "Half Moon",
    "52": "Knee",
    "53": "Bounce",
    "54": "Throw Away",
    "55": "Emblem Toss",
    "56": "Slam",
    "18": "Flare Blade",
    "19": "Double-Edge Dance",
    "20": "Blazer",
    "21": "Counter",
    "50": "Getup Attack",
    "51": "Getup Attack",
    "61": "Edge Attack",
    "62": "Edge Attack"
},
  "Diddy Kong": {
    "1": "Item Throw",
    "2": "Right Slap",
    "3": "Left Slap",
    "4": "Foot Push",
    "5": "Tail Whip",
    "6": "Rolling Slap",
    "7": "Double Punch",
    "8": "Overhead Slap",
    "9": "Hand Clap",
    "10": "Slap & Beat",
    "11": "Triple Attack",
    "12": "Flashy Flare",
    "13": "Diddy Roll",
    "14": "Screw Kick",
    "15": "Quick Backspin",
    "16": "Turn Kick",
    "17": "Hammer Meteor Knuckle",
    "18": "Peanut Popgun",
    "19": "Monkey Flip",
    "20": "Rocketbarrel Boost",
    "21": "Banana Peel",
    "50": "Getup Attack",
    "51": "Getup Attack",
    "52": "Grab Pummel",
    "53": "Rock Throw",
    "54": "Back Rock Throw",
    "55": "Grab Kick",
    "56": "Leap Frog",
    "61": "Edge Attack",
    "62": "Edge Attack"
},
  "Wolf": {
    "1": "Item Throw",
    "2": "Jab",
    "3": "Straight",
    "5": "Rapid Kick",
    "6": "Dash Attack",
    "7": "Dual Slash",
    "8": "Back Kick",
    "9": "Wolf Tail",
    "10": "Wolf Crash",
    "11": "Flip Kick",
    "12": "Gust Slash",
    "13": "Flying Kick",
    "14": "Quick Slash",
    "15": "Behind Kick",
    "16": "Air Slice",
    "17": "Meteor Crash",
    "18": "Blaster",
    "19": "Wolf Flash",
    "20": "Fire Wolf",
    "21": "Reflector",
    "50": "Getup Attack",
    "51": "Getup Attack (Slow)",
    "52": "knee",
    "53": "Short Scratch",
    "54": "Scratch Upper",
    "55": "Throw Scratch",
    "56": "Bottom Down",
    "61": "Edge Attack",
    "62": "Edge Attack"
},
  "Charizard": {
    "1": "Item Throw",
    "2": "Scratch",
    "3": "Scratch",
    "4": "Wing Cutter",
    "6": "Front Kick",
    "7": "Flame Tail",
    "8": "Wing Thrust",
    "9": "Low Headbutt",
    "10": "Headlong Rush",
    "11": "Wing Bash",
    "12": "Wing Attack",
    "13": "Lizardon Turn",
    "14": "Fire Blast",
    "15": "Midair Flame Tail",
    "16": "Flying Headbutt",
    "17": "Stomp",
    "18": "Flamethrower",
    "19": "Flare Blitz",
    "20": "Fly",
    "21": "Rock Smash",
    "50": "Getup Attack",
    "51": "Getup Attack",
    "52": "Biting and Tearing",
    "53": "Biting Throw",
    "54": "Rear Biting Throw",
    "55": "Toss and Headbutt",
    "56": "Roasting Heat",
    "61": "Edge Attack",
    "62": "Edge Attack"
},
  "Lucas": {
    "1": "Item Throw",
    "2": "Short Kick",
    "3": "Reverse Kick",
    "4": "Turning Kick",
    "6": "PK Palm Push",
    "7": "PK Slash",
    "8": "PK Reverse Kick",
    "9": "Spinning Kick",
    "10": "Stick",
    "11": "PK Smash Geyser",
    "12": "PK Blow",
    "13": "PK Flying Attack",
    "14": "PK Air Front Kick",
    "15": "PK Meteor Kick",
    "16": "Jumping Headbutt",
    "17": "PK Foot Stomp",
    "18": "PK Freeze",
    "19": "PK Fire",
    "20": "PK Thunder",
    "21": "PSI Magnet",
    "50": "Getup Attack",
    "51": "Getup Attack",
    "52": "Headbutt Pummel",
    "53": "PK Throw",
    "54": "Reverse PK Throw",
    "55": "PK Lifting",
    "56": "PK Pile Driver",
    "61": "Edge Attack (Slow)",
    "62": "Edge Attack"
},
  "Sonic": {
    "1": "Item Throw",
    "2": "Jab",
    "3": "Jab",
    "4": "Kick",
    "6": "Spin Dash",
    "7": "Horse Kick",
    "8": "Double Air Kick",
    "9": "Leg Hitter",
    "10": "Wind Up Punch",
    "11": "Short Spin Attack",
    "12": "Split Kick",
    "13": "Air Spin",
    "14": "Sonic Turn",
    "15": "Back Spin Kick",
    "16": "Air Scissors",
    "17": "Shooting Star Kick",
    "18": "Homing Attack",
    "19": "Spin Dash",
    "20": "Spring Jump",
    "21": "Spin Charge",
    "50": "Getup Attack",
    "51": "Getup Attack",
    "52": "Grab Kneebutt",
    "53": "Close Kick",
    "54": "Spin Throw",
    "55": "Hedgehog Needle",
    "56": "Spinning Gear",
    "61": "Edge Attack",
    "62": "Edge Attack"
},
  "King Dedede": {
    "1": "Item Throw",
    "2": "Quick Swing",
    "3": "Swing Up",
    "5": "Battering Strike",
    "6": "Belly Flop",
    "7": "Extending Hammer",
    "8": "Great King Headbutt",
    "9": "Restful Kick",
    "10": "Megaton Hammer",
    "11": "Sweeping Hammer",
    "12": "Turning Hammer",
    "13": "Belly Drum",
    "14": "Ice Chipper",
    "15": "Shake Off",
    "16": "Up Stirring",
    "17": "Down Stirring",
    "18": "Inhale",
    "19": "Gordo Throw",
    "20": "Super Dedede Jump",
    "21": "Jet Hammer",
    "50": "Getup Attack",
    "51": "Getup Attack (Slow)",
    "52": "Grab Headbutt",
    "53": "Golf Swing",
    "54": "Reverse Golf Swing",
    "55": "Receive",
    "56": "Beatdown",
    "61": "Edge Attack",
    "62": "Edge Attack"
},
  "Tails": {
    "1": "Item Throw",
    "2": "Jab",
    "3": "Jab",
    "4": "Jab",
    "5": "Rapid Jabs",
    "6": "Dash Attack",
    "7": "Forward Tilt",
    "8": "Up Tilt",
    "9": "Down Tilt",
    "10": "Forward Smash",
    "11": "Up Smash",
    "12": "Down Smash",
    "13": "Neutral Air",
    "14": "Forward Air",
    "15": "Back Air",
    "16": "Up Air",
    "17": "Down Air",
    "18": "Neutral B",
    "19": "Side B",
    "20": "Up B",
    "21": "Down B",
    "50": "Getup Attack",
    "51": "Getup Attack (Slow)",
    "52": "Grab Pummel",
    "53": "Forward Throw",
    "54": "Back Throw",
    "55": "Up Throw",
    "56": "Down Throw",
    "57": "Cargo Forward Throw",
    "59": "Cargo Up Throw",
    "61": "Edge Attack (Slow)",
    "62": "Edge Attack"
}
}

